# Generated by Django 3.0 on 2021-06-11 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('JobPosts', '0003_auto_20210611_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Applicant_name', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_author', to='JobPosts.JobPost', verbose_name='author')),
                ('jobpost_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_title', to='JobPosts.JobPost', verbose_name='title')),
            ],
        ),
    ]
