# Generated by Django 3.0 on 2021-07-04 19:21

import ResumePost.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobPosts', '0003_auto_20210611_1158'),
        ('ResumePost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumepost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_author', to='JobPosts.JobPost', verbose_name='job_author'),
        ),
        migrations.AlterField(
            model_name='resumepost',
            name='document',
            field=models.FileField(upload_to=ResumePost.models.upload_location),
        ),
    ]
