# Generated by Django 3.0 on 2021-07-04 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResumePost', '0002_auto_20210704_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumepost',
            name='author',
        ),
    ]
